### ISSUE TITLE
Swap UI blocked by option tab

### ISSUE THREAD

**Issue by tormanburak** [solidlyexchange/solidly.exchange#11]
After picking a pair to swap, the Swap UI is extended with price info, route, price impact and swap button. The extended Swap UI is now partially blocked by the option tab (swap, liquidity, vest, etc..). There is no way to adjust the amount of first token unless refreshing the page.

![solidly bug](https://user-images.githubusercontent.com/25334152/155879803-7b15e217-29a1-445b-8da2-6886bda5123e.PNG)

**Comment by tormanburak** [comment]
Kind of tiny laptop, 15 inch screen. No problem at all, it looks great overall!

**Comment by antonnell** [comment]
Fixed with b2e909468c7120ff2b6dcdfd53383e41adf2b424
You should be able to scroll top to bottom to access what you need to.
