### ISSUE TITLE
Bug - Custom addresses won't work on token search bar

### ISSUE THREAD

**Issue by naomsa** [solidlyexchange/solidly.exchange#16]

**Comment by antonnell** [comment]
It is working on my end, but i wasn't working like 2 days ago, could you re-test and let me know what address you are using for the search?
make sure you are on the latest version 0.0.30

**Comment by Ceazor** [comment]
I would suggest a CRTL F5 (on PC) or CMD SHIFT R (on MAC) for a hard refresh. 
Hard refreshes should be your goto troubleshoot

**Comment by antonnell** [comment]
"Devs do something" is the goto troubleshoot. Don't be silly.
I generally assume it is something I fucked up anyway.

**Comment by antonnell** [comment]
Not this sick token I found on ftm scan.
![image](https://user-images.githubusercontent.com/38530524/155884491-cdfdcce3-c606-442c-b800-dc89eb9e49ef.png)

**Comment by Ceazor** [comment]
We all drop the ball in this wild wild west. 
Little extra 0 here, a little over looked update there, a clickity click everywhere

**Comment by naomsa** [comment]
It works now, sorry for not testing before
