### ISSUE TITLE
Error: Deposit tokens in the pool / execution reverted:   BaseV1Router: EXPIRED

### ISSUE THREAD

**Issue by praise-you** [solidlyexchange/solidly.exchange#19]
Hello,

### Issue:
On pressing "Deposit & Stake" the following error shows up:
`Error: Deposit tokens in the pool / execution reverted:   BaseV1Router: EXPIRED`

### The process is composed of 5 stages:
1. Allow the router to spend your USDC
2. Allowance on OXD sufffcient
3. Allowance on vAMM-USDC/OXD
4. Deposit token in the pool
5. Stake LP tokens in the gauge

### Steps I went through:
- Choose "Add liquidity to vAMM-USDC/OXD"
- Enter amounts
- Leave slippage at 2%
- Press "Deposit & Stake"
- Endure multiple errors before the one reported here:
1. Error: Nonce too low
2. Repeat then one asset will go through but not the other
3. Repeat process to get the other approved
4. Repeat again to validate stage number 4/5 "Deposit token in the pool"
- `Error: Deposit tokens in the pool / execution reverted:   BaseV1Router: EXPIRED`
- This error shows up before Metamask or Frame are activated.
- Refreshing doesn't help.

Many many thanks

<img width="281" alt="ttt" src="https://user-images.githubusercontent.com/67846246/155892660-b4afb321-9360-4c2c-a922-5b6070c69ffe.png">

**Comment by praise-you** [comment]
Dear dev, I forgot to ask my question: What do I do to solve this issue?
Thanks

**Comment by praise-you** [comment]
Another test with a new wallet address and I got the same error.

**Comment by antonnell** [comment]
Expired means that the tx didn't execute before the deadline.
Deadline is calculated as current time + 600 seconds.

It might be that your system time is incorrect? Not sure really

**Comment by antonnell** [comment]
Glad I could help you.
