### ISSUE TITLE
Loading time of the liquidity pools columns is either failing or very random

### ISSUE THREAD

**Issue by praise-you** [solidlyexchange/solidly.exchange#20]
Hello,

### Issue:
Loading the liquidity pools columns is either failing, very slow or instant.

Sometimes the colums "Wallet", "My pool amount" and "Total pool amount" charge instantly but "Total pool staked" and "My staked amount" do not.

### Tested on:
- Linux: Brave, Vivaldi, Opera & Firefox
- Windows: Firefox

### An example:
![ttttt](https://user-images.githubusercontent.com/67846246/155893639-0a224a32-6f73-49f3-89c4-807bb5712908.jpg)

**Comment by antonnell** [comment]
Yea, so data loading is a bit of a bitch with the RPC nodes being sketchy.
I've implemented re-tries and made some other optimisations for data loading so it should be a bit better.

If things are still bad for you, try using the ankr RPC nodes. They seem more stable.

**Comment by praise-you** [comment]
Thanks for optimizing this. The website is quicker now with Ankr.
