### ISSUE TITLE
UI issue; Unable to check rewards and manage liquidity

### ISSUE THREAD

**Issue by llagostectte** [solidlyexchange/solidly.exchange#25]
Hi everybody; 

It the first time I actually write a post on this site, so please forgive if my style lacks any of the standards.
I believe my issue is kind of related with the one named "Issue claiming bribes" from "pain-ftm" user.

Details:
Brave/Metamask
Added liquidity and stacked on a pool.

After being able to add liquidity and stake ( not using any third party device/api) in USDC/DAI Solidly pool, I am able to check my liquidity position but not to check if I've earned any rewards. Moreover I am not able to withdraw my liquidity. 

When I check my rewards appears the following message:
**Error: Internal JSON-RPC error. { "code": -32000, "message": "header not found" }**

When I visit the liquidity tab, I am able to see my position, but when I press the "manage liquidity" button, my position does not appear anywhere, it just shows a banner which reminds the user to withdraw any reward before any liquidity is removed.

I've tried many things like clear the cache or change the rpc but the error persists. 

Thank you for your cooperation. Best Regards

**Comment by antonnell** [comment]
Header not found is an error that Metamask returns from the RPCc nodes.

It happens extremely often with https://rpc.ftm.tools/
If you change your RPC to https://rpc.ankr.com/fantom it shouldn't give that error anymore.

Did you deposit your LP or did you stake it in the Gauge?

**Comment by llagostectte** [comment]
Hi I really appreciate your cooperation;

Two questions:
1-how do I know the **rpc** you are suggesting is a legitimate rpc? ( maybe it is just me but I am not able to find a  legitimate source,-like for example the Fantom foundation-  providing such info). If you know any side please would be nice to share it, thx.
2-I do not know what you mean with the **gauge.** If you are referring at locking the SOLID, the answer is no. I just placed my liquidity in the pool: first you add liquidity and the it gives the option to stake it, so I pressed the stake button. At that moment I did not have any SOLID token ( I do not know now).

Thank you very much for your help I'll let you know if this worked.


Thn

**Comment by RoastedCashew** [comment]
I have tried both the Ankr RPC and the rpc tools, and neither allow me to claim my bribes. I get the same JSON error and the transaction never reaches metamask. I am able to claim my LP fees and solidly rewards with no problem.

**Comment by llagostectte** [comment]
Hi Antonnell and co;

I've tried the ankr rpc, and the error message disappears. 

Anyway, I am not able to reach my liquidity, as I explained before, I may see it in the liquidity tab but it appears to be 0.00 when I enter the "manage liquidity" section. Inside, I may see the banner about collecting the rewards before removing liquidity, and the withdraw buttons remind off) .
I've tried to check my position with vfat.tools and USDC-DAI pool does not appear, seems like only specific pools (voted) appear there.

Thanks for your cooperation. Regards

**Comment by llagostectte** [comment]
The issue was solved!

It was just a noob mistake.
When you actually get in to the manage liquidity section, your tokens, in order to be shown., You have to press the Balance button, under the Manage liquidity Pair title. Then your tokens will appear and you'll be able to operate.

Thanks for  your cooperation.

**Comment by antonnell** [comment]
Gucci, glad you got it sorted
